apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: v1-web
  labels:
    version: v1
    env: prod
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: env
        operator: In
        values:
          - dev
          - prod
  template:
    metadata:
      name: v1-web
      labels:
        version: v1
        env: prod
    spec:
      containers:
        - image: amantuladhar/docker-kubernetes:v1-web
          name: v1-web
          livenessProbe:
            httpGet:
              path: /test/
              port: 8080
          ports:
            - containerPort: 8080
