version: '3'
services:
  myapp:
    image: amantuladhar/doc-kub-ws:web-basic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/test"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s