version: '3'
services:
  myapp:
    image: amantuladhar/doc-kub-ws:web-basic
    ports:
      - 9090:8080
  mydb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=docker_kubernetes