version: '3'
services:
  myapp:
    image: amantuladhar/doc-kub-ws:web-basic
    ports:
      - 9090:8080
    networks:
      - myNet
  myTester:
    image: amantuladhar/network-tools
    command: sleep 50000 # Doing this so that this container runs longer
    network_mode: service:myapp
networks:
  myNet: