version: '3'
services:
  myapp:
    image: amantuladhar/doc-kub-ws:withdb-basic
    ports:
      - 9090:8080
    networks:
      - myNet
    environment:
      - DB_URL=jdbc:mysql://mydb:3306/docker_kubernetes?useSSL=false
      - DB_USER=root
      - DB_PASS=password
    depends_on:
      - mydb
  mydb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=docker_kubernetes
    networks:
      - myNet
    volumes:
      - "./volume/mysql-compose/:/var/lib/mysql/"
networks:
  myNet: