apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
  labels:
    env: prod
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 40
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      env: prod
  # Pod template from here on out
  template:
    metadata:
      name: mypod
      labels:
        env: prod
    spec:
      containers:
        - image: amantuladhar/doc-kub-ws:web-basic-v2 #image: amantuladhar/doc-kub-ws:web-basic -> amantuladhar/doc-kub-ws:web-basic-v2
          name: mycontainer
          readinessProbe:
            httpGet:
              path: /test/status-5xx # path: /test -> /test/status-5xx
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 1
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 8080
  selector:
    env: prod
