apiVersion: v1
kind: Pod
metadata:
  name: v1-web
  labels:
    version: v1
    env: dev
spec:
  containers:
    - image: amantuladhar/doc-kub-ws:web-basic
      name: v1-web
      livenessProbe:
        initialDelaySeconds: 10
        periodSeconds: 60
        timeoutSeconds: 5
        failureThreshold: 3
        httpGet:
          port: 8080
          path: /test
      ports:
        - containerPort: 8080