apiVersion: v1
kind: Pod
metadata:
  name: v1web
  labels:
    version: v1
    env: dev
spec:
  containers:
    - image: amantuladhar/doc-kub-ws:web-basic
      name: v1web
      livenessProbe:
        httpGet:
          port: 8080
          path: /test
      ports:
        - containerPort: 8080