apiVersion: v1
kind: Pod
metadata:
  name: mydb-po
  labels:
    app: mydb
spec:
  # Volume Properties
  volumes:
    - name: volume-name
      hostPath:
        path: /Users/tulada/Desktop/Box/Aman/Workshop/volume/kub-mysql
  containers:
    - image: mysql:5.7
      name: mydb-co
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: docker_kubernetes
      # Which Volume & Where
      volumeMounts:
          - name: volume-name
            mountPath: /var/lib/mysql/
